name: Build and Publish ComputerInfo

on:
  push:
    branches:
      - main
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish --self-contained --runtime win-x64

    - name: Create Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ./publish/ComputerInfo.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
