name: Build, Tag & Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for tagging

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Restore dependencies
      run: dotnet restore src/ComputerInfo/ComputerInfo.csproj

    - name: Build
      run: dotnet build --configuration Release --no-restore src/ComputerInfo/ComputerInfo.csproj

    - name: Publish
      run: dotnet publish src/ComputerInfo/ComputerInfo.csproj --configuration Release --output publish --no-restore

    - name: Read Version from Props
      id: version
      run: |
        $version = Select-String -Path src/ComputerInfo/version.props -Pattern "<BaseVersion>(.*)</BaseVersion>" | ForEach-Object { $_.Matches.Groups[1].Value }
        $build = Select-String -Path src/ComputerInfo/version.props -Pattern "<BuildNumber>(.*)</BuildNumber>" | ForEach-Object { $_.Matches.Groups[1].Value }
        $tag = "v$version.$build"
        echo "tag=$tag" >> $env:GITHUB_OUTPUT

    - name: Create Git Tag
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@users.noreply.github.com"
        git tag ${{ steps.version.outputs.tag }}
        git push origin ${{ steps.version.outputs.tag }}

    - name: Zip Published App
      run: Compress-Archive -Path publish\* -DestinationPath ComputerInfo.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.tag }}
        name: Release ${{ steps.version.outputs.tag }}
        files: ComputerInfo.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
